import { Outfitter, Hunt, HuntStatistics, OutfitterChat, OutfitterDocument } from './types';

export const mockOutfitter: Outfitter = {
  id: 'OUT001',
  fullName: 'James McKenzie',
  company: 'Bushveld Safari Outfitters',
  email: 'james@bushveldsafaris.co.za',
  phone: '+27 82 555 1234',
  country: 'South Africa',
  province: 'Limpopo',
  city: 'Thabazimbi',
  farmName: 'Kalahari Game Reserve',
  status: 'approved',
  documents: [
    {
      id: 'DOC001',
      type: 'outfitter-licence',
      fileName: 'professional-hunter-licence-2024.pdf',
      uploadDate: '2024-01-15',
      expiryDate: '2025-12-31',
      status: 'valid',
    },
    {
      id: 'DOC002',
      type: 'hunting-permit',
      fileName: 'hunting-permit-limpopo.pdf',
      uploadDate: '2024-01-15',
      expiryDate: '2024-12-15',
      status: 'expiring-soon',
    },
    {
      id: 'DOC003',
      type: 'id-copy',
      fileName: 'id-copy.pdf',
      uploadDate: '2024-01-15',
      status: 'valid',
    },
    {
      id: 'DOC004',
      type: 'insurance-certificate',
      fileName: 'liability-insurance-2024.pdf',
      uploadDate: '2024-02-01',
      expiryDate: '2025-01-31',
      status: 'valid',
    },
  ],
  registeredDate: '2023-06-10',
  lastActive: '2024-11-03',
};

export const mockHunts: Hunt[] = [
  {
    id: 'HUNT001',
    name: 'Spring Plains Game Safari 2024',
    outfitterId: 'OUT001',
    hunterId: 'HNT001',
    hunterName: 'John Hunter',
    region: 'Northern Province',
    province: 'Limpopo',
    farm: 'Kalahari Game Reserve',
    startDate: '2024-09-15',
    endDate: '2024-09-22',
    animalCount: 5,
    animals: ['Kudu', 'Impala', 'Warthog', 'Springbok', 'Gemsbok'],
    status: 'completed',
    notes: 'Excellent hunt, all animals taken ethically',
    registerDocument: 'hunt-register-sept-2024.pdf',
    createdAt: '2024-09-01',
    updatedAt: '2024-09-22',
  },
  {
    id: 'HUNT002',
    name: 'Buffalo & Plains Game Package',
    outfitterId: 'OUT001',
    hunterId: 'HNT002',
    hunterName: 'Michael Thompson',
    region: 'Northern Province',
    province: 'Limpopo',
    farm: 'Waterberg Wilderness',
    startDate: '2024-10-10',
    endDate: '2024-10-17',
    animalCount: 4,
    animals: ['Cape Buffalo', 'Nyala', 'Waterbuck', 'Eland'],
    status: 'completed',
    registerDocument: 'hunt-register-oct-2024.pdf',
    createdAt: '2024-09-20',
    updatedAt: '2024-10-17',
  },
  {
    id: 'HUNT003',
    name: 'November Trophy Hunt',
    outfitterId: 'OUT001',
    hunterId: 'HNT003',
    hunterName: 'Robert Anderson',
    region: 'Northern Province',
    province: 'Limpopo',
    farm: 'Kalahari Game Reserve',
    startDate: '2024-11-05',
    endDate: '2024-11-12',
    animalCount: 6,
    animals: ['Kudu', 'Sable Antelope', 'Wildebeest', 'Zebra', 'Impala', 'Warthog'],
    status: 'active',
    notes: 'Hunt in progress',
    createdAt: '2024-10-15',
    updatedAt: '2024-11-04',
  },
  {
    id: 'HUNT004',
    name: 'December Safari Package',
    outfitterId: 'OUT001',
    hunterName: 'David Williams',
    region: 'Northern Province',
    province: 'Limpopo',
    farm: 'Kalahari Game Reserve',
    startDate: '2024-12-10',
    endDate: '2024-12-17',
    animalCount: 3,
    animals: ['Kudu', 'Gemsbok', 'Springbok'],
    status: 'planned',
    createdAt: '2024-11-01',
    updatedAt: '2024-11-02',
  },
];

export const mockHuntStatistics: HuntStatistics = {
  totalHuntsThisYear: 18,
  totalHuntersGuided: 15,
  totalAnimalsHarvested: 62,
  mostCommonSpecies: 'Kudu',
  topHuntingLocation: 'Kalahari Game Reserve',
};

export const mockOutfitterChats: OutfitterChat[] = [
  {
    id: 'CHAT001',
    participantId: 'HNT001',
    participantName: 'John Hunter',
    participantType: 'hunter',
    lastMessage: 'Thanks for the amazing hunt! Looking forward to seeing my trophies.',
    lastMessageTime: '2024-11-02T14:30:00',
    unread: 0,
  },
  {
    id: 'CHAT002',
    participantId: 'TAX001',
    participantName: 'APEX Taxidermy',
    participantType: 'taxidermy',
    lastMessage: 'All specimens from Hunt HUNT002 have been received and are in processing.',
    lastMessageTime: '2024-11-03T09:15:00',
    unread: 1,
  },
  {
    id: 'CHAT003',
    participantId: 'HNT003',
    participantName: 'Robert Anderson',
    participantType: 'hunter',
    lastMessage: 'What time should I arrive at the lodge tomorrow?',
    lastMessageTime: '2024-11-03T16:45:00',
    unread: 2,
  },
  {
    id: 'CHAT004',
    participantId: 'ADM001',
    participantName: 'APEX Admin',
    participantType: 'admin',
    lastMessage: 'Your hunting permit is expiring soon. Please upload renewal.',
    lastMessageTime: '2024-11-01T10:00:00',
    unread: 1,
  },
];

export const animalsBySpecies = [
  { species: 'Kudu', count: 12 },
  { species: 'Impala', count: 15 },
  { species: 'Warthog', count: 8 },
  { species: 'Springbok', count: 6 },
  { species: 'Gemsbok', count: 5 },
  { species: 'Cape Buffalo', count: 3 },
  { species: 'Sable Antelope', count: 2 },
  { species: 'Nyala', count: 4 },
  { species: 'Waterbuck', count: 3 },
  { species: 'Eland', count: 2 },
  { species: 'Wildebeest', count: 1 },
  { species: 'Zebra', count: 1 },
];

export const huntsByMonth = [
  { month: 'Jan', hunts: 2 },
  { month: 'Feb', hunts: 1 },
  { month: 'Mar', hunts: 3 },
  { month: 'Apr', hunts: 2 },
  { month: 'May', hunts: 4 },
  { month: 'Jun', hunts: 1 },
  { month: 'Jul', hunts: 2 },
  { month: 'Aug', hunts: 1 },
  { month: 'Sep', hunts: 1 },
  { month: 'Oct', hunts: 0 },
  { month: 'Nov', hunts: 1 },
  { month: 'Dec', hunts: 0 },
];

export const huntersByVolume = [
  { hunter: 'John Hunter', hunts: 3 },
  { hunter: 'Michael Thompson', hunts: 2 },
  { hunter: 'Robert Anderson', hunts: 2 },
  { hunter: 'David Williams', hunts: 1 },
  { hunter: 'James Wilson', hunts: 2 },
];
